services:
  - type: cron
    name: ukraine-job-agent-daily
    env: python
    buildCommand: pip install requests
    startCommand: python worker.py --daily
    schedule: "0 10 * * *"
    envVars:
      - key: TO_EMAIL
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false

  - type: cron
    name: ukraine-job-agent-weekly
    env: python
    buildCommand: pip install requests
    startCommand: python worker.py --weekly
    schedule: "0 10 * * 0"
    envVars:
      - key: TO_EMAIL
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
